services:
  rabbit:
    container_name: rabbitmq
    tty: true
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_USER: admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  
  application:
    image: application
    ports:
      - "80:80"
    build:
      context: .
      args:
        MODE: ${MODE-Debug}
      dockerfile: Application/Dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit

  csharp-compiler-service:
    image: csharp-compiler-service
    build:
      context: .
      no_cache: true
      args:
        MODE: ${MODE-Debug}
      dockerfile: CompilerService/Dockerfile
    restart: on-failure
    privileged: true
    pid: "host"
    depends_on:
      - rabbit
    links:
       - rabbit
    
    