# This is a generated file. Not intended for manual editing.
services:
  application:
    build:
      context: "H:\\RiderProjects\\VirtualProgrammingLab"
      dockerfile: "Application/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net6.0/Application.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net6.0/Application.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\segro_c4h97pj\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\segro_c4h97pj\\.nuget\\packages"
    image: "application:dev"
    ports: []
    volumes:
    - "C:\\Users\\segro_c4h97pj\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "H:\\RiderProjects\\VirtualProgrammingLab\\Application:/app:rw"
    - "H:\\RiderProjects\\VirtualProgrammingLab:/src:rw"
    working_dir: "/app"
