name: Dev Deploy App

on:
  push:
    branches:
      - "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    env:
      HOST: root@94.228.117.181
      RABBITMQ_HOST: rabbitmq
      DEPLOY_DIRECTORY: /root/apps/vpl
      ENV_FILE_PATH: /root/apps/vpl/config.env
      MODE: Release
      APP_PORT: 9090
      DEFAULT_ADMIN_EMAIL: admin@segrom.ru
      INPUT_QUEUE_NAME_FORMAT: CompileQueue[{0}]
      RESULTS_QUEUE_NAME_FORMAT: ResultsQueue[{0}]
      COMPILE_RESULTS_UPDATE_QUEUE_NAME: ResultsUpdateQueue
      DB_CONNECTIONSTRING: Username=application;Password=AppP4SS_wrd;Host=database;Port=5432;Database=applicationdb;Connection Lifetime=0;

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove old directory
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          rm ${{ env.DEPLOY_DIRECTORY }} -Rf"
      - name: Deploy to VM
        run: |
          sudo apt-get install -y ssh rsync
          echo "$DEPLOY_SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "mkdir -p ${{ env.DEPLOY_DIRECTORY }}"
          rsync -avz -e 'ssh -i deploy_key.pem -o StrictHostKeyChecking=no' --exclude='.git' ./ ${{ env.HOST }}:${{ env.DEPLOY_DIRECTORY }}
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Update apt
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          sudo apt-get update &&\
          sudo apt-get install -y ca-certificates curl &&\
          sudo install -m 0755 -d /etc/apt/keyrings &&\
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc &&\
          sudo chmod a+r /etc/apt/keyrings/docker.asc &&\
          
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&\
          sudo apt-get update"
      - name: Install docker
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin"
      - name: Create environment file on server
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          touch ${{ env.ENV_FILE_PATH }} && \
          chmod 600 ${{ env.ENV_FILE_PATH }} && \
          echo 'MODE=${{ env.MODE }}' > ${{ env.ENV_FILE_PATH }} && \
          echo 'APP_PORT=${{ env.APP_PORT }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'DB_CONNECTIONSTRING=${{ env.DB_CONNECTIONSTRING }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'RABBITMQ_HOST=${{ env.RABBITMQ_HOST }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'INPUT_QUEUE_NAME_FORMAT=${{ env.INPUT_QUEUE_NAME_FORMAT }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'RESULTS_QUEUE_NAME_FORMAT=${{ env.RESULTS_QUEUE_NAME_FORMAT }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'COMPILE_RESULTS_UPDATE_QUEUE_NAME=${{ env.COMPILE_RESULTS_UPDATE_QUEUE_NAME }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'DEFAULT_ADMIN_EMAIL=${{ env.DEFAULT_ADMIN_EMAIL }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'DEFAULT_ADMIN_NAME=${{ secrets.DEFAULT_ADMIN_NAME }}' >> ${{ env.ENV_FILE_PATH }} && \
          echo 'DEFAULT_ADMIN_PASSWORD=${{ secrets.DEFAULT_ADMIN_PASSWORD }}' >> ${{ env.ENV_FILE_PATH }}"
      
      - name: Build the stack
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          docker compose -f ${{ env.DEPLOY_DIRECTORY }}/docker-compose.yml --env-file ${{ env.ENV_FILE_PATH }} build"
      - name: Run compose
        run: |
          ssh -i deploy_key.pem -o StrictHostKeyChecking=no ${{ env.HOST }} "\
          docker compose -f ${{ env.DEPLOY_DIRECTORY }}/docker-compose.yml --env-file ${{ env.ENV_FILE_PATH }} up -d "